spring:
  application:
    name: employee-management-ddd
  profiles:
    active: dev

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # JMS Configuration
  artemis:
    mode: embedded
    embedded:
      enabled: true
      persistent: false

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hr-payroll-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Security Configuration
security:
  jwt:
    secret: your-secret-key-change-this-in-production-minimum-256-bits-required
    expiration: 86400000 # 24 hours in milliseconds

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    kafka:
      enabled: true
    db:
      enabled: true

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Application Configuration
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200
  events:
    kafka:
      enabled: true
      topic-prefix: hr-payroll
    jms:
      enabled: true
      queue-prefix: hr.payroll

# Logging Configuration
logging:
  level:
    root: INFO
    com.hrpayroll: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
