spring:
  datasource:
    url: jdbc:h2:mem:hrpayrolldb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

security:
  jwt:
    secret: dev-secret-key-for-development-only-min-256-bits-required-for-hs256

logging:
  level:
    com.hrpayroll: DEBUG
    org.springframework.web: DEBUG
    org.springframework.validation: TRACE
