apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrpayroll-app
  namespace: hrpayroll
  labels:
    app: hrpayroll
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hrpayroll
  template:
    metadata:
      labels:
        app: hrpayroll
    spec:
      containers:
      - name: hrpayroll
        image: hrpayroll/employee-management-ddd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: hrpayroll-config
        - secretRef:
            name: hrpayroll-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: hrpayroll-service
  namespace: hrpayroll
spec:
  type: LoadBalancer
  selector:
    app: hrpayroll
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
